# Generated by Django 6.0.6 on 2026-07-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('crypto', 'Crypto'), ('gold', 'Gold'), ('trading', 'Trading (Equity)')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('volume', models.DecimalField(decimal_places=8, max_digits=20)),
                ('avg_buy_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('buy_timestamp', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-buy_timestamp'],
            },
        ),
    ]
