# Generated by Django 6.0.6 on 2026-07-02 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('rating_score', models.PositiveSmallIntegerField()),
                ('qualitative_feedback', models.CharField(max_length=1000)),
                ('primary_market_focus', models.CharField(choices=[('crypto', 'Crypto'), ('gold', 'Gold'), ('trading', 'Trading')], max_length=10)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
