# Generated by Django 6.0.6 on 2026-07-02 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('meta_description', models.CharField(blank=True, default='', max_length=500)),
                ('og_image', models.CharField(blank=True, default='', max_length=500)),
                ('canonical_uri', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO meta rule',
                'verbose_name_plural': 'SEO meta rules',
                'ordering': ['path'],
            },
        ),
    ]
