# Generated by Django 6.0.6 on 2026-07-26 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('action', models.CharField(choices=[('buy', 'Buy / Long'), ('sell', 'Sell / Close'), ('short', 'Short'), ('hold', 'Hold (Observation)')], max_length=10)),
                ('symbol', models.CharField(max_length=20)),
                ('asset_type', models.CharField(default='crypto', max_length=10)),
                ('entry_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('volume', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('emotion', models.CharField(choices=[('confident', '😎 Confident'), ('fearful', '😰 Fearful'), ('fomo', '🔥 FOMO'), ('revenge', '😤 Revenge Trade'), ('disciplined', '🧘 Disciplined'), ('greedy', '🤑 Greedy'), ('uncertain', '🤔 Uncertain')], default='disciplined', max_length=15)),
                ('outcome', models.CharField(choices=[('profit', 'Profit ✅'), ('loss', 'Loss ❌'), ('breakeven', 'Breakeven ↔️'), ('open', 'Still Open 🔄')], default='open', max_length=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
