# Generated by Django 6.0.6 on 2026-10-04 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(db_index=True, default='news', max_length=32)),
                ('source_id', models.CharField(db_index=True, max_length=64)),
                ('chunk_index', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(blank=True, db_index=True, max_length=32)),
                ('source_name', models.CharField(blank=True, max_length=120)),
                ('published_at', models.CharField(blank=True, max_length=64)),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(default=list)),
                ('embedding_model', models.CharField(max_length=80)),
                ('content_hash', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['source_type', 'source_id', 'chunk_index'],
                'constraints': [models.UniqueConstraint(fields=('source_type', 'source_id', 'chunk_index'), name='rag_unique_chunk')],
            },
        ),
    ]
